imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: false

#swiftmailer:
#    delivery_address: me@example.com

twig:
    debug: true
    cache: false